### PR TITLE
Improve text and markup for the Terms of Use card

### PR DESCRIPTION
**Pull request by oltionchampari**
Closes Caleydo/tdp_bi_bioinfodb#1221

### Summary 
In the code I have commented out a version of the list using the `flush group list` from bootstrap, which in my opinion looks cleaner.
Maybe you can decide which one to keep.
#### v1
 
grafik1

#### v2

grafik2

### CODE REVIEW

**Review by thinkh — CHANGES_REQUESTED** [review]
Thanks for the two variants. I also prefer the list group variant and go for it. (Though we might have to change it later if the customer does not like it.)

@oltionchampari Please have a look at the following errors in the developer console. They need to be fixed before proceeding with this PR.

grafik

```
react-dom.development.js:88 Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (created by ForwardRef)
    in ForwardRef (created by ListGroupItem)
    in ListGroupItem (created by HelpPage)
    in div (created by ForwardRef)
    in ForwardRef (created by ListGroup)
    in ListGroup (created by HelpPage)
    in p (created by CardText)
    in CardText (created by HelpPage)
    in div (created by CardBody)
    in CardBody (created by HelpPage)
    in div (created by Card)
    in Card (created by HelpPage)
    in div (created by ElementWrapper)
    in ElementWrapper (created by Element)
    in Element (created by HelpPage)
    in div (created by Col)
    in Col (created by HelpPage)
    in div (created by Row)
    in Row (created by HelpPage)
    in div (created by Col)
    in Col (created by HelpPage)
    in div (created by Row)
    in Row (created by HelpPage)
    in div (created by Container)
    in Container (created by HelpPage)
    in HelpPage
    in Route
    in Switch
    in Router (created by HashRouter)
    in HashRouter
printWarning @ react-dom.development.js:88
error @ react-dom.development.js:60
validateDOMNesting @ react-dom.development.js:7383
createInstance @ react-dom.development.js:7479
completeWork @ react-dom.development.js:18970
completeUnitOfWork @ react-dom.development.js:22192
performUnitOfWork @ react-dom.development.js:22165
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
scheduleUpdateOnFiber @ react-dom.development.js:21188
updateContainer @ react-dom.development.js:24373
(anonymous) @ react-dom.development.js:24758
unbatchedUpdates @ react-dom.development.js:21903
legacyRenderSubtreeIntoContainer @ react-dom.development.js:24757
render @ react-dom.development.js:24840
UzAk @ initialize.welcome.tsx:11
__webpack_require__ @ bootstrap:84
3 @ welcome.c68843897c4aa33f57ea.js:24
__webpack_require__ @ bootstrap:84
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ welcome.c68843897c4aa33f57ea.js:11
webpackUniversalModuleDefinition @ universalModuleDefinition:9
(anonymous) @ universalModuleDefinition:10
react-dom.development.js:88 Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (created by ForwardRef)
    in ForwardRef (created by ListGroup)
    in ListGroup (created by HelpPage)
    in p (created by CardText)
    in CardText (created by HelpPage)
    in div (created by CardBody)
    in CardBody (created by HelpPage)
    in div (created by Card)
    in Card (created by HelpPage)
    in div (created by ElementWrapper)
    in ElementWrapper (created by Element)
    in Element (created by HelpPage)
    in div (created by Col)
    in Col (created by HelpPage)
    in div (created by Row)
    in Row (created by HelpPage)
    in div (created by Col)
    in Col (created by HelpPage)
    in div (created by Row)
    in Row (created by HelpPage)
    in div (created by Container)
    in Container (created by HelpPage)
    in HelpPage
    in Route
    in Switch
    in Router (created by HashRouter)
    in HashRouter
```

**Comment by thinkh** [comment]
P.S. also with the unordered list variant I get an error:

grafik


```
Warning: validateDOMNesting(...): <ul> cannot appear as a descendant of <p>.
    in ul (created by HelpPage)
    in p (created by CardText)
    in CardText (created by HelpPage)
    in div (created by CardBody)
    in CardBody (created by HelpPage)
    in div (created by Card)
    in Card (created by HelpPage)
    in div (created by ElementWrapper)
    in ElementWrapper (created by Element)
    in Element (created by HelpPage)
    in div (created by Col)
    in Col (created by HelpPage)
    in div (created by Row)
    in Row (created by HelpPage)
    in div (created by Col)
    in Col (created by HelpPage)
    in div (created by Row)
    in Row (created by HelpPage)
    in div (created by Container)
    in Container (created by HelpPage)
    in HelpPage
    in Route
    in Switch
    in Router (created by HashRouter)
    in HashRouter
```

**Review by thinkh — APPROVED** [review]
Removing the `<Card.Text>` fixes the nested `div` in `p` error.

**Comment by oltionchampari** [comment]
> Removing the `<Card.Text>` fixes the nested `div` in `p` error.

Thanks, for fixing this

**Pull request merged**
