### PR TITLE
Update content of the What's new page

### PR DESCRIPTION
**Pull request by oltionchampari**
Closes Caleydo/tdp_bi_bioinfodb#1236

### Summary 

* Added the updated content to the What's New page.
* Did not update the design, but that is something that we have to do.
### Screenshot

grafik

Note: This branch has the old scrollspy implementation, so before we merge this we need to merge https://github.com/Caleydo/ordino_public/pull/97 and resolve the conflicts.

### CODE REVIEW

**Comment by thinkh** [comment]
@oltionchampari Did you update the screenshots with high resolution ones already?

**Review by thinkh — APPROVED** [review]
I split the large card into multiple small cards with headings. In my opinion it looks lighter now. What do you think?

localhost_8080_

**Comment by thinkh** [comment]
> Note: This branch has the old scrollspy implementation, so before we merge this we need to merge #97 and resolve the conflicts.

@oltionchampari Please update the screenshots and take care about updating and merging this PR after PR #97 has been merged. Thanks.

**Comment by oltionchampari** [comment]
Splitting the cards is definitely an improvement. I am waiting on https://github.com/Caleydo/ordino_public/pull/97 to continue here

**Pull request merged**
